### ISSUE TITLE
Requesting Attachments of Documents

### ISSUE THREAD

**Issue by Jayaram-JD** [Jayaram-G/WhatsUp_Development#3]
Dear Jayaram ,

It would be great if the app is capable of attaching the documents as well,
Kindly add the feature.

**Comment by Jayaram-G** [comment]
Dear jai , Thanks for suggesting this feature. We will add and let you know.

**Comment by Jayaram-G** [comment]
Dear Jai, Thanks for your valuable suggestion. This feature is going to make our product great.
